-- 异世界传说 老库升级脚本（2026-08-09）
-- 在已部署的 yishijie 库上执行一次即可
USE yishijie;

ALTER TABLE mail ADD COLUMN rewards_json TEXT NULL AFTER coins;

ALTER TABLE exchange_listings
  ADD COLUMN category VARCHAR(16) NOT NULL DEFAULT 'item' AFTER item_name,
  ADD COLUMN pet_json TEXT NULL AFTER category,
  ADD KEY idx_category (category);

CREATE TABLE IF NOT EXISTS redeem_codes (
  code VARCHAR(40) NOT NULL PRIMARY KEY,
  rewards_json TEXT NOT NULL,
  max_uses INT NOT NULL DEFAULT 1,
  used_count INT NOT NULL DEFAULT 0,
  expires_at DATETIME NULL,
  description VARCHAR(255) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS redeem_uses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(40) NOT NULL,
  player_id VARCHAR(20) NOT NULL,
  used_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_code_player (code, player_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS pvp_ratings (
  player_id VARCHAR(20) NOT NULL PRIMARY KEY,
  rating INT NOT NULL DEFAULT 1000,
  wins INT NOT NULL DEFAULT 0,
  losses INT NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS pvp_matches (
  id INT AUTO_INCREMENT PRIMARY KEY,
  attacker_id VARCHAR(20) NOT NULL,
  defender_id VARCHAR(20) NOT NULL,
  attacker_win TINYINT NOT NULL DEFAULT 0,
  rating_delta INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_attacker (attacker_id),
  KEY idx_defender (defender_id)
) ENGINE=InnoDB;

ALTER TABLE users ADD COLUMN name_changed_at DATETIME NULL;

CREATE TABLE IF NOT EXISTS banned_fingerprints (
  fingerprint VARCHAR(128) NOT NULL PRIMARY KEY,
  reason VARCHAR(255) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
